name: RechenStar
options:
  bundleIdPrefix: ch.rechenstar
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "1540"
  minimumXcodeGenVersion: "2.38"
  generateEmptyDirectories: true
  objectVersion: 56

settings:
  base:
    SWIFT_VERSION: "5.10"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.2"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
    INFOPLIST_KEY_CFBundleDisplayName: "RechenStar"
    INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO

targets:
  RechenStar:
    type: application
    platform: iOS
    sources:
      - path: RechenStar
        excludes:
          - "**/.DS_Store"
    configFiles:
      Debug: BuildNumber.xcconfig
      Release: BuildNumber.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ch.rechenstar.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_IDENTITY: "iPhone Developer"
        DEVELOPMENT_TEAM: 97M8QABMLM

  RechenStarTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RechenStarTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: RechenStar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rechenstar.tests
        GENERATE_INFOPLIST_FILE: YES
        DEVELOPMENT_TEAM: 97M8QABMLM

  RechenStarUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: RechenStarUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: RechenStar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rechenstar.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: RechenStar
        DEVELOPMENT_TEAM: 97M8QABMLM
