name: RechenStar
options:
  bundleIdPrefix: com.rechenstar
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "1540"
  minimumXcodeGenVersion: "2.38"
  generateEmptyDirectories: true
  objectVersion: 56

settings:
  base:
    SWIFT_VERSION: "5.10"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
    INFOPLIST_KEY_CFBundleDisplayName: "RechenStar"

targets:
  RechenStar:
    type: application
    platform: iOS
    sources:
      - path: RechenStar
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rechenstar.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_IDENTITY: "iPhone Developer"
        DEVELOPMENT_TEAM: 79DD3LF864
    postBuildScripts:
      - name: Set Build Number
        script: |
          BUILD_NUMBER=$(git rev-list --count HEAD)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"

  RechenStarTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RechenStarTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: RechenStar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rechenstar.tests
        GENERATE_INFOPLIST_FILE: YES
